### PR TITLE
enable daily cron (ubuntu)

### PR DESCRIPTION
**Pull request by acurvers**

### CODE REVIEW

**Comment by acurvers** [comment]
perhaps needs a flag to execute the task or not
like updatedb_cron: <default:daily|hourly|weekly> etc

**Comment by tersmitten** [comment]
Can you explain what this does / why this change is needed?

**Comment by acurvers** [comment]
perhaps its just on my machine that the daily cron was disabled, i will check that first, thanks

**Comment by tersmitten** [comment]
At least not for me:

```
# ll /etc/cron.daily/
total 56K
-rwxr-xr-x 1 root root  376 Mar 31  2016 apport*
-rwxr-xr-x 1 root root 1.5K Jun 19  2017 apt-compat*
-rwxr-xr-x 1 root root  314 Nov 27  2015 aptitude*
-rwxr-xr-x 1 root root  355 May 22  2012 bsdmainutils*
-rwxr-xr-x 1 root root 1.6K Nov 27  2015 dpkg*
-rwxr-xr-x 1 root root  372 May  6  2015 logrotate*
-rwxr-xr-x 1 root root 1.3K Nov  6  2015 man-db*
-rwxr-xr-x 1 root root  539 Jul 16  2014 mdadm*
-rwxr-xr-x 1 root root  435 Nov 18  2014 mlocate*
-rwxr-xr-x 1 root root 1.4K Sep  5  2017 ntp*
-rwxr-xr-x 1 root root  249 Nov 12  2015 passwd*
-rwxr-xr-x 1 root root 3.4K Feb 26  2016 popularity-contest*
-rwxr-xr-x 1 root root  441 Jan 27  2016 sysstat*
-rwxr-xr-x 1 root root  214 May 24  2016 update-notifier-common*
```

```
# ll /etc/cron.daily/
total 60K
-rwxr-xr-x 1 root root  376 Nov 11  2019 apport*
-rwxr-xr-x 1 root root 1.5K Apr 20  2018 apt-compat*
-rwxr-xr-x 1 root root  314 Jan 17  2018 aptitude*
-rwxr-xr-x 1 root root  355 Dec 29  2017 bsdmainutils*
-rwxr-xr-x 1 root root 1.2K Nov  2  2017 dpkg*
-rwxr-xr-x 1 root root  372 Aug 21  2017 logrotate*
-rwxr-xr-x 1 root root 1.1K Apr  7  2018 man-db*
-rwxr-xr-x 1 root root  539 Jan 14  2020 mdadm*
-rwxr-xr-x 1 root root  538 Mar  1  2018 mlocate*
-rwxr-xr-x 1 root root 1.4K Dec 13  2017 ntp*
-rwxr-xr-x 1 root root  249 Jan 25  2018 passwd*
-rwxr-xr-x 1 root root 3.4K Feb 21  2018 popularity-contest*
-rwxr-xr-x 1 root root  441 Dec 23  2017 sysstat*
-rwxr-xr-x 1 root root  246 Mar 21  2018 ubuntu-advantage-tools*
-rwxr-xr-x 1 root root  214 Nov 12  2018 update-notifier-common*
```

**Pull request closed without merging**
